default_config:

logger:
  default: info
  logs:
    custom_components.localtuya: debug

recorder:
  db_url: !secret homeassistant_db_url

lovelace:
  mode: yaml
  resources:
    # HACS
    - url: /local/mushroom.js
      type: module
    - url: /local/button-card.js
      type: module
    - url: /local/hui-element.js
      type: module
    - url: /local/community/universal-remote-card/universal-remote-card.min.js
      type: module
    # my custom resources
    - url: /local/vacuum-card.js
      type: module
    - url: /local/layout-card.js
      type: module
    - url: /local/air-purifier-card.js?v=1.0.27
      type: module
    - url: /local/red-circle-card.js?v=1.0.18
      type: module
    - url: /local/philips-tower-fan-control.js?v=1.0.7
      type: module
    - url: /local/auto-card.js?v=1.1.0
      type: module


  dashboards:
    electricity-insights:
      mode: yaml
      filename: dashboard_views/electricity_insights_dashboard.yaml
      title: Electricity Insights
      icon: mdi:flash
      show_in_sidebar: true

sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: rest
    name: Watermeter Total Volume
    resource: http://192.168.178.253/api/v1/data
    value_template: "{{ value_json.total_liter_m3 }}"
    unit_of_measurement: "m³"
    device_class: water
    icon: mdi:water
    state_class: total_increasing
    scan_interval: 30
  - platform: rest
    name: Watermeter Current Flow
    resource: http://192.168.178.253/api/v1/data
    value_template: "{{ value_json.active_liter_lpm }}"
    unit_of_measurement: "L/min"
    device_class: volume_flow_rate
    icon: mdi:water-pump
    state_class: measurement
    scan_interval: 30
  - platform: rest
    name: Watermeter WiFi Strength
    resource: http://192.168.178.253/api/v1/data
    value_template: "{{ value_json.wifi_strength }}"
    unit_of_measurement: "%"
    device_class: signal_strength
    icon: mdi:wifi
    state_class: measurement
    scan_interval: 60
  - platform: rest
    name: Watermeter Total Offset
    resource: http://192.168.178.253/api/v1/data
    value_template: "{{ value_json.total_liter_offset_m3 }}"
    unit_of_measurement: "m³"
    device_class: water
    icon: mdi:water
    state_class: total_increasing
    scan_interval: 30


plant: !include plants.yaml

frontend:
  themes: !include_dir_merge_named themes/

template: !include_dir_merge_list templates/

script: !include_dir_merge_named scripts/

automation: !include automations.yaml

scene: !include_dir_merge_named scenes/

utility_meter: !include_dir_merge_named utility_meter/

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.0/16
    #- 172.19.0.8
  # Optionally, if you have a certificate and want to enforce SSL
  # ssl_certificate: /config/fullchain.pem
  # ssl_key: /config/privkey.pem

google_assistant:
  project_id: home-assistant-tafbar
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
