default_config:

recorder:
  db_url: !secret homeassistant_db_url

lovelace:
  mode: yaml
  resources:
    # HACS
    - url: /local/mushroom.js
      type: module
    - url: /local/button-card.js
      type: module
    # my custom resources
    - url: /local/vacuum-card.js
      type: module
    - url: /local/layout-card.js
      type: module
    - url: /local/air-purifier-card.js?v=1.0.27
      type: module
    - url: /local/red-circle-card.js?v=1.0.18
      type: module
    - url: /local/philips-tower-fan-control.js?v=1.0.7
      type: module

  dashboards:
    electricity-insights:
      mode: yaml
      filename: dashboard_views/electricity_insights_dashboard.yaml
      title: Electricity Insights
      icon: mdi:flash
      show_in_sidebar: true

frontend:
  themes: !include_dir_merge_named themes/
template: !include_dir_merge_list templates/
script: !include_dir_merge_named scripts/
automation: !include_dir_merge_named automations/
scene: !include_dir_merge_named scenes/
utility_meter: !include_dir_merge_named utility_meter/

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.11 # The IP address of your reverse proxy
    - 172.19.0.19
  # Optionally, if you have a certificate and want to enforce SSL
  # ssl_certificate: /config/fullchain.pem
  # ssl_key: /config/privkey.pem

google_assistant:
  project_id: home-assistant-tafbar
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
