default_config:
recorder:
  db_url: !secret homeassistant_db_url
lovelace:
  mode: yaml
  resources:
    - url: /local/vacuum-card.js
      type: module
    - url: /local/layout-card.js
      type: module
    - url: /local/air-purifier-card.js?v=1.0.3
      type: module

script: !include_dir_merge_named scripts/

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.11 # The IP address of your reverse proxy
    - 172.19.0.19
  # Optionally, if you have a certificate and want to enforce SSL
  # ssl_certificate: /config/fullchain.pem
  # ssl_key: /config/privkey.pem

google_assistant:
  project_id: home-assistant-tafbar
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
